---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-echo-values-nginx-config
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        server {
          listen 8080;
          root /usr/share/nginx/html;
        }
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;

        keepalive_timeout  65;

        # include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: debug-echo-values-config
data:
  values.yaml: |-
    
    global:
      baseValue: from-base-value
      overriddenValue: from-base-value
    image:
      pullPolicy: IfNotPresent
      repository: nginx
      tag: 1.27.2
    replicaCount: 1
---
apiVersion: v1
kind: Service
metadata:
  name: debug-echo-values
  labels:
    app.kubernetes.io/name: echo-values
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: echo-values
    app.kubernetes.io/instance: debug
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-echo-values
  labels:
    app.kubernetes.io/name: echo-values
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo-values
      app.kubernetes.io/instance: debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo-values
    spec:
      containers:
        - name: echo-values
          image: "nginx:1.27.2"
          command: [nginx-debug, '-g', 'daemon off;']
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/index.html
              subPath: values.yaml
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: debug-echo-values-config
        - name: nginx-config-volume
          configMap:
            name: debug-echo-values-nginx-config
