apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: trivy-additional-values
    files:
      - values.yaml=trivy-additional-values.yaml
    options:
      disableNameSuffixHash: true

