apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: trivy-additional-secrets
    files:
      - values.yaml=trivy-additional-secrets.yaml
    options:
      disableNameSuffixHash: true

resources:
  - artifactory.yaml