apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/CICDior/secrets.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging/kind-local-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-trivy-operator
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/trivy-operator
  dependsOn:
    - name: secrets
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/valuesFrom
          value:
            - kind: ConfigMap
              name: trivy-additional-values
              optional: false
      target:
        kind: HelmRelease
        name: trivy-operator
        namespace: trivy-operator
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers-reloader
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers/reloader
  dependsOn:
    - name: secrets
  prune: true
  wait: true
  patches:
    - patch: |
        - op: add
          path: /spec/valuesFrom
          value:
            - kind: ConfigMap
              name: reloader-additional-values
              optional: false
      target:
        kind: HelmRelease
        name: reloader
        namespace: reloader
    - patch: |
        - op: add
          path: /spec/dependsOn
          value:
            - name: reloader
              namespace: reloader
      target:
        kind: HelmRelease
        name: trivy-operator
        namespace: trivy-operator
