---
apiVersion: v1
kind: Namespace
metadata:
  name: echo-values
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cicdior
  namespace: echo-values
spec:
  interval: 1h
  url: https://cicdior.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-values
  namespace: echo-values
spec:
  interval: 2m
  chart:
    spec:
      chart: echo-values
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: cicdior
        namespace: echo-values
      interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: echo-additional-values
      optional: true
  values:
    global:
      overriddenValue: from-inline-values
      inlineValue: from-inline-values
    trivy:
      httpProxy: http://10.32.230.10:3128
      noProxy: 10.244.0.0/16,10.96.0.0/12,0.0.0.0,localhost,127.0.0.1
