---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 24h
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    description: |
      Helm chart for prometheus.
spec:
  interval: 2m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "65.8.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 1m
  values:
    alertmanager:
      enabled: false
    grafana:
      enabled: false
    prometheus:
      service:
        type: NodePort
        nodePort: 30090
      thanosService:
        enabled: false
      prometheusSpec:
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        podMonitorNamespaceSelector:
          matchLabels:
            prometheus-monitoring: "enabled"
        serviceMonitorNamespaceSelector:
          matchLabels:
            prometheus-monitoring: "enabled"