---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: reloader
spec:
  interval: 24h
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: reloader
  annotations:
    description: |
      Helm chart for config map and secret reloader. For chart details see
      https://github.com/stakater/Reloader/tree/master/deployments/kubernetes/chart/reloader
spec:
  interval: 2m
  chart:
    spec:
      chart: reloader
      version: "1.1.0"
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: reloader
      interval: 10m
  values:
    reloader:
      reloadStrategy: annotations
      watchGlobally: false
      logLevel: debug
      logFormat: json
      readOnlyRootFileSystem: true
      deployment:
        securityContext:
          fsGroup: 3000
          runAsGroup: 10000
          runAsUser: 10003
          seccompProfile:
            type: RuntimeDefault
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
            - CAP_NET_RAW
          procMount: Default
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        livenessProbe:
          timeoutSeconds: 5
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          timeoutSeconds: 15
          failureThreshold: 5
          periodSeconds: 10
          successThreshold: 1
        resources:
         limits:
           cpu: "100m"
           memory: "512Mi"
         requests:
           cpu: "10m"
           memory: "128Mi"
