---
apiVersion: v1
kind: Namespace
metadata:
  name: trivy-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aquasecurity
  namespace: trivy-operator
spec:
  interval: 24h
  url: https://aquasecurity.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-operator
  annotations:
    description: |
      Helm chart the trivy operator. For chart details see
      https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
spec:
  suspend: false
  interval: 2m
  chart:
    spec:
      chart: trivy-operator
      version: "0.24.1"
      sourceRef:
        kind: HelmRepository
        name: aquasecurity
        namespace: trivy-operator
      interval: 10m
