apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: reloader-additional-values
    files:
      - values.yaml=reloader-additional-values.yaml
    options:
      disableNameSuffixHash: true
