apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: trivy-additional-values
    files:
      - values.yaml=trivy-additional-values.yaml
    options:
      disableNameSuffixHash: true

patches:
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: trivy-operator
        namespace: trivy-operator
        annotations:
          configmap.reloader.stakater.com/reload: trivy-additional-values
    target:
      kind: Deployment
      name: trivy-operator
      namespace: trivy-operator
