targetNamespaces: "examples"
targetWorkloads: "replicaset"

operator:
  annotations:
    configmap.reloader.stakater.com/reload: "trivy-additional-values"
  scannerReportTTL: "100m"
  scanJobTTL: "20m"
  scanSecretTTL: "20m"
  scanJobTimeout: "20m"
  logDevMode: true
  httpProxy: http://10.32.230.10:3128
  httpsProxy: http://10.32.230.10:3128
  noProxy: trivy-processor-trivy-processor.trivy-operator.svc.cluster.local,10.244.0.0/16,10.96.0.0/12,0.0.0.0,localhost,127.0.0.1
  webhookBroadcastURL: http://trivy-processor-trivy-processor.trivy-operator.svc.cluster.local/report
trivyOperator:
  scanJobCompressLogs: false
  scanJobPodTemplatePodSecurityContext:
    runAsGroup: 10003
    runAsUser: 10003
    runAsNonRoot: true
    fsGroup: 3000
    seccompProfile:
      type: RuntimeDefault
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
    privileged: false
    readOnlyRootFilesystem: true
trivy:
  resources:
    requests:
      cpu: 100m
      memory: 500M
    limits:
      cpu: 500m
      memory: 1Gi
  debug: true
  skipJavaDBUpdate: false
  httpProxy: http://10.32.230.10:3128
  httpsProxy: http://10.32.230.10:3128
  noProxy: trivy-processor-trivy-processor.trivy-operator.svc.cluster.local,10.244.0.0/16,10.96.0.0/12,0.0.0.0,localhost,127.0.0.1
rbac:
  create: true
