targetNamespaces: "examples"
operator:
  scannerReportTTL: "5m"
  scanJobTTL: "5m"
  scanSecretTTL: "5m"
  logDevMode: true
  httpProxy: http://10.32.230.10:3128
  httpsProxy: http://10.32.230.10:3128
  noProxy: 10.244.0.0/16,10.96.0.0/12,0.0.0.0,localhost,127.0.0.1
trivyOperator:
    scanJobPodTemplatePodSecurityContext: {}
    scanJobPodTemplateContainerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
            drop:
                - ALL
        privileged: false
        readOnlyRootFilesystem: true
    # -- scanJobCustomVolumesMount add custom volumes mount to the scan job
    scanJobCustomVolumesMount:
      - name: trivy-cache
        mountPath: /tmp/trivy/.cache
        readOnly: false

    # -- scanJobCustomVolumes add custom volumes to the scan job
    scanJobCustomVolumes:
      - name: trivy-cache
        persistentVolumeClaim:
          claimName: trivy-cache
trivy:
    debug: true
    skipJavaDBUpdate: false
    httpProxy: http://10.32.230.10:3128
    httpsProxy: http://10.32.230.10:3128
    noProxy: 10.244.0.0/16,10.96.0.0/12,0.0.0.0,localhost,127.0.0.1
rbac:
    create: true
