targetNamespaces: "examples"
targetWorkloads: "replicaset"

operator:
  annotations:
    configmap.reloader.stakater.com/reload: "trivy-additional-values"
  scannerReportTTL: "100m"
  scanJobTTL: "20m"
  scanSecretTTL: "20m"
  scanJobTimeout: "20m"
  logDevMode: true
#  webhookBroadcastURL: http://trivy-processor-trivy-processor.trivy-operator.svc.cluster.local/report
trivyOperator:
  scanJobPodTemplatePodSecurityContext:
    runAsGroup: 10003
    runAsUser: 10003
    runAsNonRoot: true
    fsGroup: 3000
    seccompProfile:
      type: RuntimeDefault
  scanJobPodTemplateContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
        drop:
            - ALL
    privileged: false
    readOnlyRootFilesystem: true
trivy:
  resources:
    requests:
      cpu: 100m
      memory: 500M
    limits:
      cpu: 500m
      memory: 1Gi
  debug: true
  skipJavaDBUpdate: false
rbac:
  create: true
