kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-local-6
networking:
  disableDefaultCNI: true  # disable kindnet
  podSubnet: "192.168.0.0/16"  # Calico's default subnet
  serviceSubnet: "10.96.0.0/12"
nodes:
  - role: control-plane
  - role: worker